version: '2'

services:
   ansible-server:
     image: "ubuntu:16.04"
     command: tail -f /dev/null
     ports:
       - "8000:80"
     links:
       - node1:node1
       - node2:node2
     volumes:
      - ./ansible-config:/etc/ansible
   node1:
     image: "ubuntu:16.04"
     command: tail -f /dev/null
     ports:
       - "8001:80"
     restart: always
   node2:
     image: "ubuntu:16.04"
     command: tail -f /dev/null
     ports:
       - "8002:80"
     restart: always
